name: CI
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: sudosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build:
    name: Build and test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub get

      - name: Run tests
        uses: steebchen/flutter@v1.1.0
        with:
          args: test

      - name: Build apk
        uses: steebchen/flutter@v1.1.0
        with:
          args: build apk --release
