# This is a basic workflow to help you get started with Actions

name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Build
        run: flutter build apk

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
